#!/bin/bash
# This file is automatically executed by KDM, GDM and XDM.
# Source it in .xinitrc manually or have a rule in xinit.d!

dirname="$(dirname $(readlink --canonicalize .xprofile))"
source ${dirname}/bash.d/config.sh

source /etc/X11/xinit/xinitrc.d/30-dbus
eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)
export GNOME_KEYRING_CONTROL GNOME_KEYRING_PID GPG_AGENT_INFO SSH_AUTH_SOCK

(xhost +local: &) &>/dev/null
xmodmap /home/milan/.Xmodmap &
sudo hdmi-switch &
sudo trackpoint-init
