#!/bin/bash
# This file is automatically executed by KDM, GDM and XDM.
# Source it in .xinitrc manually or have a rule in xinit.d!

dirname="$(dirname $(readlink --canonicalize .xprofile))"
source ${dirname}/bash.d/config.sh
source /etc/X11/xinit/xinitrc.d/30-dbus

(xhost +local: &) &>/dev/null
xmodmap /home/milan/.Xmodmap &
